### ISSUE TITLE
Never use the current font in a palette plugin

### ISSUE THREAD

**Issue by schriftgestalt** [HugoJourdan/Color-Flow#3]
https://github.com/HugoJourdan/Color-Flow/blob/db844783af95fcaa1e230c636ef5f60874624eb9/Color%20Flow.glyphsPalette/Contents/Resources/plugin.py#L43

Always use `self.windowController()` to access the properties of the window that contains the palette. The most important properties are: `self.windowController().documentFont()` and `self.windowController().selectedLayers()`

And the `settings()` method should be used to set up the UI, not the data. Put that into an `update()` method (that you already have).
That call it from from `setWindowController_()`:
```
def setWindowController_(self, windowController):
		try:
			if hasattr(self, "_windowController") and self._windowController is windowController:
				return
			self._windowController = windowController
			self.update()
		except:
			print(traceback.format_exc())
```

**Comment by schriftgestalt** [comment]
see also here: https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/Python%20Templates/Palette#other-useful-functions

**Comment by HugoJourdan** [comment]
Thanks, I fixed it.
