### ISSUE TITLE
Checkbox Error

### ISSUE THREAD

**Issue by gorjious** [HugoJourdan/Color-Flow#6]
When I first try to check a Checkbox, I am getting this error message.

<img width="748" alt="Screenshot 2022-10-13 at 11 50 09" src="https://user-images.githubusercontent.com/23149420/195669830-09bdce69-1b35-4a45-b32b-b88854ca733b.png">

Then the box is shown as checked but it doesn't register the count. 
Also, the source name in the color flow textbox doesn't match the source in edit view.

<img width="292" alt="Screenshot 2022-10-13 at 11 53 06" src="https://user-images.githubusercontent.com/23149420/195670222-2b639be6-580b-4c30-90fd-e97746a58ccc.png">

It was working fine before but I recently updated to Glyphs 3.1.1 (3140) and reinstalled Color Flow from the plugin manager.

**Comment by gorjious** [comment]
On a new file. Things seem to work fine on one master. Then when another master is added there is some strange behavior that you'll see in the video. It's like it is not recognizing the second master and keeping the same settings. The name stays on Regular. A error pops up towards the end.

[Screen Recording 2022-10-13 at 13.24.42.zip](https://github.com/HugoJourdan/Color-Flow/files/9780098/Screen.Recording.2022-10-13.at.13.24.42.zip)

**Comment by gorjious** [comment]
This is a weird one too when the master names are the same...adding and removing checkmarks somehow gets the count going into the negatives.

[Screen Recording 2022-10-13 at 13.27.39.zip](https://github.com/HugoJourdan/Color-Flow/files/9780108/Screen.Recording.2022-10-13.at.13.27.39.zip)

**Comment by gorjious** [comment]
Started with a blank Regular and Bold masters but it still wasn't recognizing when switching masters. 

[Screen Recording 2022-10-13 at 13.41.12.zip](https://github.com/HugoJourdan/Color-Flow/files/9780141/Screen.Recording.2022-10-13.at.13.41.12.zip)

**Comment by gorjious** [comment]
Tried adding more masters, and after 2 more it suddenly recognizes the last one and first one. Really strange. 

[Screen Recording 2022-10-13 at 13.50.32.zip](https://github.com/HugoJourdan/Color-Flow/files/9780201/Screen.Recording.2022-10-13.at.13.50.32.zip)

**Comment by HugoJourdan** [comment]
Hi fixed UI update problem when switching to master recently added/duplicated.

Just one issue still happen when user duplicate existing master.
It's seem that ColorFlow can't correctly copy data from master duplicated.

A solution is to :
1. Run "Reset Color Flow Data" for duplicated master
2. Run "Copy Color Flow to master"
